# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import ChannelSummaryFields


class ChannelList(BaseModel):
    channels: Optional[list["ChannelListChannels"]]


ChannelListChannels = ChannelSummaryFields
ChannelList.model_rebuild()
