# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import ChannelSummaryFields


class ChannelBySlug(BaseModel):
    channel: Optional["ChannelBySlugChannel"]


ChannelBySlugChannel = ChannelSummaryFields
ChannelBySlug.model_rebuild()
