# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Any, Optional, Union

from .async_base_client import AsyncBaseClient
from .base_model import UNSET, UnsetType
from .channel_by_id import ChannelById
from .channel_by_slug import ChannelBySlug
from .channel_list import ChannelList
from .collection_add_products import CollectionAddProducts
from .collection_create import CollectionCreate
from .collection_update import CollectionUpdate
from .customer_by_id import CustomerById
from .customer_create import CustomerCreate
from .customer_update import CustomerUpdate
from .input_types import (
    CollectionCreateInput,
    CollectionInput,
    CustomerInput,
    CustomerOrderWhereInput,
    OrderFulfillInput,
    ProductChannelListingUpdateInput,
    ProductCreateInput,
    ProductInput,
    ProductOrder,
    ProductVariantChannelListingAddInput,
    ProductVariantCreateInput,
    ProductVariantInput,
    ProductVariantWhereInput,
    ProductWhereInput,
    PromotionCreateInput,
    PromotionRuleCreateInput,
    PromotionRuleUpdateInput,
    PromotionUpdateInput,
    StockFilterInput,
    StockInput,
    UserCreateInput,
)
from .me import Me
from .order_by_id import OrderById
from .order_cancel import OrderCancel
from .order_fulfill import OrderFulfill
from .order_ownership_by_id import OrderOwnershipById
from .orders_by_customer import OrdersByCustomer
from .product_by_id import ProductById
from .product_by_slug import ProductBySlug
from .product_channel_listing_update import ProductChannelListingUpdate
from .product_create import ProductCreate
from .product_list import ProductList
from .product_update import ProductUpdate
from .promotion_by_id import PromotionById
from .promotion_create import PromotionCreate
from .promotion_rule_create import PromotionRuleCreate
from .promotion_rule_update import PromotionRuleUpdate
from .promotion_update import PromotionUpdate
from .stock_list import StockList
from .variant_by_id import VariantById
from .variant_by_sku import VariantBySku
from .variant_channel_listing_update import VariantChannelListingUpdate
from .variant_create import VariantCreate
from .variant_list import VariantList
from .variant_stocks_create import VariantStocksCreate
from .variant_stocks_update import VariantStocksUpdate
from .variant_update import VariantUpdate


def gql(q: str) -> str:
    return q


class Client(AsyncBaseClient):
    async def collection_create(
        self, input: CollectionCreateInput, **kwargs: Any
    ) -> CollectionCreate:
        query = gql("""
            mutation CollectionCreate($input: CollectionCreateInput!) {
              collectionCreate(input: $input) {
                collection {
                  id
                  name
                  slug
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="CollectionCreate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CollectionCreate.model_validate(data)

    async def collection_update(
        self, id: str, input: CollectionInput, **kwargs: Any
    ) -> CollectionUpdate:
        query = gql("""
            mutation CollectionUpdate($id: ID!, $input: CollectionInput!) {
              collectionUpdate(id: $id, input: $input) {
                collection {
                  id
                  name
                  slug
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="CollectionUpdate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CollectionUpdate.model_validate(data)

    async def collection_add_products(
        self, collectionId: str, products: list[str], **kwargs: Any
    ) -> CollectionAddProducts:
        query = gql("""
            mutation CollectionAddProducts($collectionId: ID!, $products: [ID!]!) {
              collectionAddProducts(collectionId: $collectionId, products: $products) {
                collection {
                  id
                  name
                  slug
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "collectionId": collectionId,
            "products": products,
        }
        response = await self.execute(
            query=query,
            operation_name="CollectionAddProducts",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return CollectionAddProducts.model_validate(data)

    async def customer_create(
        self, input: UserCreateInput, **kwargs: Any
    ) -> CustomerCreate:
        query = gql("""
            mutation CustomerCreate($input: UserCreateInput!) {
              customerCreate(input: $input) {
                user {
                  ...CustomerMutationFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment CustomerMutationFields on User {
              id
              email
              firstName
              lastName
              isActive
              languageCode
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="CustomerCreate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CustomerCreate.model_validate(data)

    async def customer_update(
        self, id: str, input: CustomerInput, **kwargs: Any
    ) -> CustomerUpdate:
        query = gql("""
            mutation CustomerUpdate($id: ID!, $input: CustomerInput!) {
              customerUpdate(id: $id, input: $input) {
                user {
                  ...CustomerMutationFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment CustomerMutationFields on User {
              id
              email
              firstName
              lastName
              isActive
              languageCode
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="CustomerUpdate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CustomerUpdate.model_validate(data)

    async def variant_stocks_create(
        self, variantId: str, stocks: list[StockInput], **kwargs: Any
    ) -> VariantStocksCreate:
        query = gql("""
            mutation VariantStocksCreate($variantId: ID!, $stocks: [StockInput!]!) {
              productVariantStocksCreate(variantId: $variantId, stocks: $stocks) {
                productVariant {
                  id
                  sku
                }
                errors {
                  field
                  message
                  code
                  index
                }
              }
            }
            """)
        variables: dict[str, object] = {"variantId": variantId, "stocks": stocks}
        response = await self.execute(
            query=query,
            operation_name="VariantStocksCreate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return VariantStocksCreate.model_validate(data)

    async def variant_stocks_update(
        self, variantId: str, stocks: list[StockInput], **kwargs: Any
    ) -> VariantStocksUpdate:
        query = gql("""
            mutation VariantStocksUpdate($variantId: ID!, $stocks: [StockInput!]!) {
              productVariantStocksUpdate(variantId: $variantId, stocks: $stocks) {
                productVariant {
                  id
                  sku
                }
                errors {
                  field
                  message
                  code
                  index
                }
              }
            }
            """)
        variables: dict[str, object] = {"variantId": variantId, "stocks": stocks}
        response = await self.execute(
            query=query,
            operation_name="VariantStocksUpdate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return VariantStocksUpdate.model_validate(data)

    async def order_cancel(self, id: str, **kwargs: Any) -> OrderCancel:
        query = gql("""
            mutation OrderCancel($id: ID!) {
              orderCancel(id: $id) {
                order {
                  id
                  number
                  status
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="OrderCancel", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return OrderCancel.model_validate(data)

    async def order_fulfill(
        self, orderId: str, input: OrderFulfillInput, **kwargs: Any
    ) -> OrderFulfill:
        query = gql("""
            mutation OrderFulfill($orderId: ID!, $input: OrderFulfillInput!) {
              orderFulfill(order: $orderId, input: $input) {
                order {
                  id
                  number
                  status
                }
                fulfillments {
                  id
                  status
                  trackingNumber
                  lines {
                    id
                    quantity
                    orderLine {
                      id
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"orderId": orderId, "input": input}
        response = await self.execute(
            query=query, operation_name="OrderFulfill", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return OrderFulfill.model_validate(data)

    async def product_create(
        self, input: ProductCreateInput, **kwargs: Any
    ) -> ProductCreate:
        query = gql("""
            mutation ProductCreate($input: ProductCreateInput!) {
              productCreate(input: $input) {
                product {
                  id
                  name
                  slug
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="ProductCreate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductCreate.model_validate(data)

    async def product_update(
        self, id: str, input: ProductInput, **kwargs: Any
    ) -> ProductUpdate:
        query = gql("""
            mutation ProductUpdate($id: ID!, $input: ProductInput!) {
              productUpdate(id: $id, input: $input) {
                product {
                  id
                  name
                  slug
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="ProductUpdate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductUpdate.model_validate(data)

    async def product_channel_listing_update(
        self, id: str, input: ProductChannelListingUpdateInput, **kwargs: Any
    ) -> ProductChannelListingUpdate:
        query = gql("""
            mutation ProductChannelListingUpdate($id: ID!, $input: ProductChannelListingUpdateInput!) {
              productChannelListingUpdate(id: $id, input: $input) {
                product {
                  id
                  channelListings {
                    channel {
                      id
                      slug
                      currencyCode
                    }
                    isPublished
                    publishedAt
                    visibleInListings
                    isAvailableForPurchase
                    availableForPurchaseAt
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="ProductChannelListingUpdate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return ProductChannelListingUpdate.model_validate(data)

    async def promotion_create(
        self, input: PromotionCreateInput, **kwargs: Any
    ) -> PromotionCreate:
        query = gql("""
            mutation PromotionCreate($input: PromotionCreateInput!) {
              promotionCreate(input: $input) {
                promotion {
                  ...PromotionSummaryFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment PromotionSummaryFields on Promotion {
              id
              name
              type
              startDate
              endDate
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="PromotionCreate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return PromotionCreate.model_validate(data)

    async def promotion_update(
        self, id: str, input: PromotionUpdateInput, **kwargs: Any
    ) -> PromotionUpdate:
        query = gql("""
            mutation PromotionUpdate($id: ID!, $input: PromotionUpdateInput!) {
              promotionUpdate(id: $id, input: $input) {
                promotion {
                  ...PromotionSummaryFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment PromotionSummaryFields on Promotion {
              id
              name
              type
              startDate
              endDate
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="PromotionUpdate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return PromotionUpdate.model_validate(data)

    async def promotion_rule_create(
        self, input: PromotionRuleCreateInput, **kwargs: Any
    ) -> PromotionRuleCreate:
        query = gql("""
            mutation PromotionRuleCreate($input: PromotionRuleCreateInput!) {
              promotionRuleCreate(input: $input) {
                promotionRule {
                  ...PromotionRuleFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment PromotionRuleFields on PromotionRule {
              id
              name
              cataloguePredicate
              orderPredicate
              rewardValue
              rewardValueType
              rewardType
              channels {
                id
                slug
                currencyCode
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query,
            operation_name="PromotionRuleCreate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return PromotionRuleCreate.model_validate(data)

    async def promotion_rule_update(
        self, id: str, input: PromotionRuleUpdateInput, **kwargs: Any
    ) -> PromotionRuleUpdate:
        query = gql("""
            mutation PromotionRuleUpdate($id: ID!, $input: PromotionRuleUpdateInput!) {
              promotionRuleUpdate(id: $id, input: $input) {
                promotionRule {
                  ...PromotionRuleFields
                }
                errors {
                  field
                  message
                  code
                }
              }
            }

            fragment PromotionRuleFields on PromotionRule {
              id
              name
              cataloguePredicate
              orderPredicate
              rewardValue
              rewardValueType
              rewardType
              channels {
                id
                slug
                currencyCode
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="PromotionRuleUpdate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return PromotionRuleUpdate.model_validate(data)

    async def variant_create(
        self, input: ProductVariantCreateInput, **kwargs: Any
    ) -> VariantCreate:
        query = gql("""
            mutation VariantCreate($input: ProductVariantCreateInput!) {
              productVariantCreate(input: $input) {
                productVariant {
                  id
                  name
                  sku
                  product {
                    id
                  }
                  trackInventory
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"input": input}
        response = await self.execute(
            query=query, operation_name="VariantCreate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VariantCreate.model_validate(data)

    async def variant_update(
        self, id: str, input: ProductVariantInput, **kwargs: Any
    ) -> VariantUpdate:
        query = gql("""
            mutation VariantUpdate($id: ID!, $input: ProductVariantInput!) {
              productVariantUpdate(id: $id, input: $input) {
                productVariant {
                  id
                  name
                  sku
                  product {
                    id
                  }
                  trackInventory
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query, operation_name="VariantUpdate", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VariantUpdate.model_validate(data)

    async def variant_channel_listing_update(
        self, id: str, input: list[ProductVariantChannelListingAddInput], **kwargs: Any
    ) -> VariantChannelListingUpdate:
        query = gql("""
            mutation VariantChannelListingUpdate($id: ID!, $input: [ProductVariantChannelListingAddInput!]!) {
              productVariantChannelListingUpdate(id: $id, input: $input) {
                variant {
                  id
                  sku
                  channelListings {
                    channel {
                      id
                      slug
                      currencyCode
                    }
                    price {
                      amount
                      currency
                    }
                  }
                }
                errors {
                  field
                  message
                  code
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "input": input}
        response = await self.execute(
            query=query,
            operation_name="VariantChannelListingUpdate",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return VariantChannelListingUpdate.model_validate(data)

    async def channel_list(self, **kwargs: Any) -> ChannelList:
        query = gql("""
            query ChannelList {
              channels {
                ...ChannelSummaryFields
              }
            }

            fragment ChannelSummaryFields on Channel {
              id
              name
              slug
              currencyCode
              isActive
              defaultCountry {
                code
                country
              }
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="ChannelList", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ChannelList.model_validate(data)

    async def channel_by_id(self, id: str, **kwargs: Any) -> ChannelById:
        query = gql("""
            query ChannelById($id: ID!) {
              channel(id: $id) {
                ...ChannelSummaryFields
              }
            }

            fragment ChannelSummaryFields on Channel {
              id
              name
              slug
              currencyCode
              isActive
              defaultCountry {
                code
                country
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="ChannelById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ChannelById.model_validate(data)

    async def channel_by_slug(self, slug: str, **kwargs: Any) -> ChannelBySlug:
        query = gql("""
            query ChannelBySlug($slug: String!) {
              channel(slug: $slug) {
                ...ChannelSummaryFields
              }
            }

            fragment ChannelSummaryFields on Channel {
              id
              name
              slug
              currencyCode
              isActive
              defaultCountry {
                code
                country
              }
            }
            """)
        variables: dict[str, object] = {"slug": slug}
        response = await self.execute(
            query=query, operation_name="ChannelBySlug", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ChannelBySlug.model_validate(data)

    async def customer_by_id(self, id: str, **kwargs: Any) -> CustomerById:
        query = gql("""
            query CustomerById($id: ID!) {
              user(id: $id) {
                ...CustomerIdentityFields
              }
            }

            fragment CustomerIdentityFields on User {
              id
              email
              firstName
              lastName
              isActive
              languageCode
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="CustomerById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return CustomerById.model_validate(data)

    async def me(self, **kwargs: Any) -> Me:
        query = gql("""
            query Me {
              me {
                ...CustomerIdentityFields
              }
            }

            fragment CustomerIdentityFields on User {
              id
              email
              firstName
              lastName
              isActive
              languageCode
            }
            """)
        variables: dict[str, object] = {}
        response = await self.execute(
            query=query, operation_name="Me", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return Me.model_validate(data)

    async def orders_by_customer(
        self,
        customerId: str,
        first: int,
        after: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[CustomerOrderWhereInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> OrdersByCustomer:
        query = gql("""
            query OrdersByCustomer($customerId: ID!, $first: Int!, $after: String, $where: CustomerOrderWhereInput) {
              user(id: $customerId) {
                id
                orders(first: $first, after: $after, where: $where) {
                  edges {
                    cursor
                    node {
                      ...OrderSummaryFields
                    }
                  }
                  pageInfo {
                    hasNextPage
                    hasPreviousPage
                    startCursor
                    endCursor
                  }
                }
              }
            }

            fragment OrderSummaryFields on Order {
              id
              number
              created
              status
              statusDisplay
              isPaid
              authorizeStatus
              chargeStatus
              channel {
                id
                slug
                currencyCode
              }
              total {
                gross {
                  amount
                  currency
                }
                net {
                  amount
                  currency
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "customerId": customerId,
            "first": first,
            "after": after,
            "where": where,
        }
        response = await self.execute(
            query=query,
            operation_name="OrdersByCustomer",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return OrdersByCustomer.model_validate(data)

    async def order_ownership_by_id(self, id: str, **kwargs: Any) -> OrderOwnershipById:
        query = gql("""
            query OrderOwnershipById($id: ID!) {
              order(id: $id) {
                id
                user {
                  id
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query,
            operation_name="OrderOwnershipById",
            variables=variables,
            **kwargs,
        )
        data = self.get_data(response)
        return OrderOwnershipById.model_validate(data)

    async def order_by_id(self, id: str, **kwargs: Any) -> OrderById:
        query = gql("""
            query OrderById($id: ID!) {
              order(id: $id) {
                ...OrderSummaryFields
                user {
                  id
                }
                shippingMethodName
                subtotal {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
                shippingPrice {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
                lines {
                  id
                  productName
                  variantName
                  productSku
                  quantity
                  quantityFulfilled
                  quantityToFulfill
                  unitPrice {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                  totalPrice {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                }
                fulfillments {
                  id
                  status
                  trackingNumber
                  created
                  lines {
                    id
                    quantity
                    orderLine {
                      id
                    }
                  }
                }
              }
            }

            fragment OrderSummaryFields on Order {
              id
              number
              created
              status
              statusDisplay
              isPaid
              authorizeStatus
              chargeStatus
              channel {
                id
                slug
                currencyCode
              }
              total {
                gross {
                  amount
                  currency
                }
                net {
                  amount
                  currency
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="OrderById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return OrderById.model_validate(data)

    async def product_list(
        self,
        channel: str,
        first: int,
        after: Union[Optional[str], UnsetType] = UNSET,
        search: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[ProductWhereInput], UnsetType] = UNSET,
        sortBy: Union[Optional[ProductOrder], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> ProductList:
        query = gql("""
            query ProductList($channel: String!, $first: Int!, $after: String, $search: String, $where: ProductWhereInput, $sortBy: ProductOrder) {
              products(
                channel: $channel
                first: $first
                after: $after
                search: $search
                where: $where
                sortBy: $sortBy
              ) {
                edges {
                  cursor
                  node {
                    ...ProductSummaryFields
                  }
                }
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
              }
            }

            fragment ProductSummaryFields on Product {
              id
              name
              slug
              thumbnail {
                url
                alt
              }
              isAvailable
              isAvailableForPurchase
              pricing {
                onSale
                displayGrossPrices
                priceRange {
                  start {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                  stop {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "channel": channel,
            "first": first,
            "after": after,
            "search": search,
            "where": where,
            "sortBy": sortBy,
        }
        response = await self.execute(
            query=query, operation_name="ProductList", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductList.model_validate(data)

    async def product_by_id(self, id: str, channel: str, **kwargs: Any) -> ProductById:
        query = gql("""
            query ProductById($id: ID!, $channel: String!) {
              product(id: $id, channel: $channel) {
                ...ProductDetailFields
              }
            }

            fragment ProductDetailFields on Product {
              ...ProductSummaryFields
              description
              category {
                id
                name
                slug
              }
              productType {
                id
                name
              }
              defaultVariant {
                id
                name
                sku
              }
            }

            fragment ProductSummaryFields on Product {
              id
              name
              slug
              thumbnail {
                url
                alt
              }
              isAvailable
              isAvailableForPurchase
              pricing {
                onSale
                displayGrossPrices
                priceRange {
                  start {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                  stop {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"id": id, "channel": channel}
        response = await self.execute(
            query=query, operation_name="ProductById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductById.model_validate(data)

    async def product_by_slug(
        self, slug: str, channel: str, **kwargs: Any
    ) -> ProductBySlug:
        query = gql("""
            query ProductBySlug($slug: String!, $channel: String!) {
              product(slug: $slug, channel: $channel) {
                ...ProductDetailFields
              }
            }

            fragment ProductDetailFields on Product {
              ...ProductSummaryFields
              description
              category {
                id
                name
                slug
              }
              productType {
                id
                name
              }
              defaultVariant {
                id
                name
                sku
              }
            }

            fragment ProductSummaryFields on Product {
              id
              name
              slug
              thumbnail {
                url
                alt
              }
              isAvailable
              isAvailableForPurchase
              pricing {
                onSale
                displayGrossPrices
                priceRange {
                  start {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                  stop {
                    gross {
                      amount
                      currency
                    }
                    net {
                      amount
                      currency
                    }
                  }
                }
              }
            }
            """)
        variables: dict[str, object] = {"slug": slug, "channel": channel}
        response = await self.execute(
            query=query, operation_name="ProductBySlug", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return ProductBySlug.model_validate(data)

    async def promotion_by_id(self, id: str, **kwargs: Any) -> PromotionById:
        query = gql("""
            query PromotionById($id: ID!) {
              promotion(id: $id) {
                ...PromotionSummaryFields
              }
            }

            fragment PromotionSummaryFields on Promotion {
              id
              name
              type
              startDate
              endDate
            }
            """)
        variables: dict[str, object] = {"id": id}
        response = await self.execute(
            query=query, operation_name="PromotionById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return PromotionById.model_validate(data)

    async def stock_list(
        self,
        first: int,
        after: Union[Optional[str], UnsetType] = UNSET,
        filter_: Union[Optional[StockFilterInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> StockList:
        query = gql("""
            query StockList($first: Int!, $after: String, $filter: StockFilterInput) {
              stocks(first: $first, after: $after, filter: $filter) {
                edges {
                  node {
                    id
                    warehouse {
                      id
                    }
                    productVariant {
                      id
                    }
                    quantity
                    quantityAllocated
                  }
                }
                pageInfo {
                  hasNextPage
                  hasPreviousPage
                  startCursor
                  endCursor
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "first": first,
            "after": after,
            "filter": filter_,
        }
        response = await self.execute(
            query=query, operation_name="StockList", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return StockList.model_validate(data)

    async def variant_list(
        self,
        productId: str,
        channel: str,
        first: int,
        attributeLimit: Any,
        after: Union[Optional[str], UnsetType] = UNSET,
        where: Union[Optional[ProductVariantWhereInput], UnsetType] = UNSET,
        **kwargs: Any,
    ) -> VariantList:
        query = gql("""
            query VariantList($productId: ID!, $channel: String!, $first: Int!, $after: String, $where: ProductVariantWhereInput, $attributeLimit: PositiveInt! = 20) {
              product(id: $productId, channel: $channel) {
                id
                productVariants(first: $first, after: $after, where: $where) {
                  edges {
                    cursor
                    node {
                      ...VariantSummaryFields
                    }
                  }
                  pageInfo {
                    hasNextPage
                    hasPreviousPage
                    startCursor
                    endCursor
                  }
                }
              }
            }

            fragment VariantSummaryFields on ProductVariant {
              id
              name
              sku
              product {
                id
                name
                slug
                isAvailable
                isAvailableForPurchase
              }
              trackInventory
              quantityAvailable
              quantityLimitPerCustomer
              pricing {
                onSale
                price {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
                priceUndiscounted {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
              }
              assignedAttributes(limit: $attributeLimit) {
                __typename
                attribute {
                  id
                  name
                  slug
                }
                ... on AssignedSingleChoiceAttribute {
                  choice: value {
                    name
                    slug
                  }
                }
                ... on AssignedMultiChoiceAttribute {
                  choices: value(limit: $attributeLimit) {
                    name
                    slug
                  }
                }
                ... on AssignedSwatchAttribute {
                  swatch: value {
                    name
                    slug
                    hexColor
                    file {
                      url
                    }
                  }
                }
                ... on AssignedPlainTextAttribute {
                  text: value
                }
                ... on AssignedNumericAttribute {
                  number: value
                }
                ... on AssignedBooleanAttribute {
                  boolean: value
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "productId": productId,
            "channel": channel,
            "first": first,
            "after": after,
            "where": where,
            "attributeLimit": attributeLimit,
        }
        response = await self.execute(
            query=query, operation_name="VariantList", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VariantList.model_validate(data)

    async def variant_by_id(
        self, id: str, channel: str, attributeLimit: Any, **kwargs: Any
    ) -> VariantById:
        query = gql("""
            query VariantById($id: ID!, $channel: String!, $attributeLimit: PositiveInt! = 20) {
              productVariant(id: $id, channel: $channel) {
                ...VariantSummaryFields
              }
            }

            fragment VariantSummaryFields on ProductVariant {
              id
              name
              sku
              product {
                id
                name
                slug
                isAvailable
                isAvailableForPurchase
              }
              trackInventory
              quantityAvailable
              quantityLimitPerCustomer
              pricing {
                onSale
                price {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
                priceUndiscounted {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
              }
              assignedAttributes(limit: $attributeLimit) {
                __typename
                attribute {
                  id
                  name
                  slug
                }
                ... on AssignedSingleChoiceAttribute {
                  choice: value {
                    name
                    slug
                  }
                }
                ... on AssignedMultiChoiceAttribute {
                  choices: value(limit: $attributeLimit) {
                    name
                    slug
                  }
                }
                ... on AssignedSwatchAttribute {
                  swatch: value {
                    name
                    slug
                    hexColor
                    file {
                      url
                    }
                  }
                }
                ... on AssignedPlainTextAttribute {
                  text: value
                }
                ... on AssignedNumericAttribute {
                  number: value
                }
                ... on AssignedBooleanAttribute {
                  boolean: value
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "id": id,
            "channel": channel,
            "attributeLimit": attributeLimit,
        }
        response = await self.execute(
            query=query, operation_name="VariantById", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VariantById.model_validate(data)

    async def variant_by_sku(
        self, sku: str, channel: str, attributeLimit: Any, **kwargs: Any
    ) -> VariantBySku:
        query = gql("""
            query VariantBySku($sku: String!, $channel: String!, $attributeLimit: PositiveInt! = 20) {
              productVariant(sku: $sku, channel: $channel) {
                ...VariantSummaryFields
              }
            }

            fragment VariantSummaryFields on ProductVariant {
              id
              name
              sku
              product {
                id
                name
                slug
                isAvailable
                isAvailableForPurchase
              }
              trackInventory
              quantityAvailable
              quantityLimitPerCustomer
              pricing {
                onSale
                price {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
                priceUndiscounted {
                  gross {
                    amount
                    currency
                  }
                  net {
                    amount
                    currency
                  }
                }
              }
              assignedAttributes(limit: $attributeLimit) {
                __typename
                attribute {
                  id
                  name
                  slug
                }
                ... on AssignedSingleChoiceAttribute {
                  choice: value {
                    name
                    slug
                  }
                }
                ... on AssignedMultiChoiceAttribute {
                  choices: value(limit: $attributeLimit) {
                    name
                    slug
                  }
                }
                ... on AssignedSwatchAttribute {
                  swatch: value {
                    name
                    slug
                    hexColor
                    file {
                      url
                    }
                  }
                }
                ... on AssignedPlainTextAttribute {
                  text: value
                }
                ... on AssignedNumericAttribute {
                  number: value
                }
                ... on AssignedBooleanAttribute {
                  boolean: value
                }
              }
            }
            """)
        variables: dict[str, object] = {
            "sku": sku,
            "channel": channel,
            "attributeLimit": attributeLimit,
        }
        response = await self.execute(
            query=query, operation_name="VariantBySku", variables=variables, **kwargs
        )
        data = self.get_data(response)
        return VariantBySku.model_validate(data)
