# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import CollectionErrorCode


class CollectionUpdate(BaseModel):
    collectionUpdate: Optional["CollectionUpdateCollectionUpdate"]


class CollectionUpdateCollectionUpdate(BaseModel):
    collection: Optional["CollectionUpdateCollectionUpdateCollection"]
    errors: list["CollectionUpdateCollectionUpdateErrors"]


class CollectionUpdateCollectionUpdateCollection(BaseModel):
    id: str
    name: str
    slug: str


class CollectionUpdateCollectionUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CollectionErrorCode


CollectionUpdate.model_rebuild()
CollectionUpdateCollectionUpdate.model_rebuild()
