# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import CollectionErrorCode


class CollectionCreate(BaseModel):
    collectionCreate: Optional["CollectionCreateCollectionCreate"]


class CollectionCreateCollectionCreate(BaseModel):
    collection: Optional["CollectionCreateCollectionCreateCollection"]
    errors: list["CollectionCreateCollectionCreateErrors"]


class CollectionCreateCollectionCreateCollection(BaseModel):
    id: str
    name: str
    slug: str


class CollectionCreateCollectionCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CollectionErrorCode


CollectionCreate.model_rebuild()
CollectionCreateCollectionCreate.model_rebuild()
