# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import CollectionErrorCode


class CollectionAddProducts(BaseModel):
    collectionAddProducts: Optional["CollectionAddProductsCollectionAddProducts"]


class CollectionAddProductsCollectionAddProducts(BaseModel):
    collection: Optional["CollectionAddProductsCollectionAddProductsCollection"]
    errors: list["CollectionAddProductsCollectionAddProductsErrors"]


class CollectionAddProductsCollectionAddProductsCollection(BaseModel):
    id: str
    name: str
    slug: str


class CollectionAddProductsCollectionAddProductsErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: CollectionErrorCode


CollectionAddProducts.model_rebuild()
CollectionAddProductsCollectionAddProducts.model_rebuild()
