# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import AccountErrorCode
from .fragments import CustomerMutationFields


class CustomerUpdate(BaseModel):
    customerUpdate: Optional["CustomerUpdateCustomerUpdate"]


class CustomerUpdateCustomerUpdate(BaseModel):
    user: Optional["CustomerUpdateCustomerUpdateUser"]
    errors: list["CustomerUpdateCustomerUpdateErrors"]


CustomerUpdateCustomerUpdateUser = CustomerMutationFields


class CustomerUpdateCustomerUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: AccountErrorCode


CustomerUpdate.model_rebuild()
CustomerUpdateCustomerUpdate.model_rebuild()
