# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import AccountErrorCode
from .fragments import CustomerMutationFields


class CustomerCreate(BaseModel):
    customerCreate: Optional["CustomerCreateCustomerCreate"]


class CustomerCreateCustomerCreate(BaseModel):
    user: Optional["CustomerCreateCustomerCreateUser"]
    errors: list["CustomerCreateCustomerCreateErrors"]


CustomerCreateCustomerCreateUser = CustomerMutationFields


class CustomerCreateCustomerCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: AccountErrorCode


CustomerCreate.model_rebuild()
CustomerCreateCustomerCreate.model_rebuild()
