# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import CustomerIdentityFields


class CustomerById(BaseModel):
    user: Optional["CustomerByIdUser"]


CustomerByIdUser = CustomerIdentityFields
CustomerById.model_rebuild()
