# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Annotated, Any, Literal, Optional, Union

from pydantic import Field

from .base_model import BaseModel
from .enums import (
    LanguageCodeEnum,
    OrderAuthorizeStatusEnum,
    OrderChargeStatusEnum,
    OrderStatus,
    PromotionTypeEnum,
    RewardTypeEnum,
    RewardValueTypeEnum,
)


class ChannelSummaryFields(BaseModel):
    id: str
    name: str
    slug: str
    currencyCode: str
    isActive: bool
    defaultCountry: "ChannelSummaryFieldsDefaultCountry"


class ChannelSummaryFieldsDefaultCountry(BaseModel):
    code: str
    country: str


class CustomerIdentityFields(BaseModel):
    id: str
    email: str
    firstName: str
    lastName: str
    isActive: bool
    languageCode: LanguageCodeEnum


class CustomerMutationFields(BaseModel):
    id: str
    email: str
    firstName: str
    lastName: str
    isActive: bool
    languageCode: LanguageCodeEnum


class OrderSummaryFields(BaseModel):
    id: str
    number: str
    created: Any
    status: OrderStatus
    statusDisplay: str
    isPaid: bool
    authorizeStatus: OrderAuthorizeStatusEnum
    chargeStatus: OrderChargeStatusEnum
    channel: "OrderSummaryFieldsChannel"
    total: "OrderSummaryFieldsTotal"


class OrderSummaryFieldsChannel(BaseModel):
    id: str
    slug: str
    currencyCode: str


class OrderSummaryFieldsTotal(BaseModel):
    gross: "OrderSummaryFieldsTotalGross"
    net: "OrderSummaryFieldsTotalNet"


class OrderSummaryFieldsTotalGross(BaseModel):
    amount: float
    currency: str


class OrderSummaryFieldsTotalNet(BaseModel):
    amount: float
    currency: str


class ProductSummaryFields(BaseModel):
    id: str
    name: str
    slug: str
    thumbnail: Optional["ProductSummaryFieldsThumbnail"]
    isAvailable: Optional[bool]
    isAvailableForPurchase: Optional[bool]
    pricing: Optional["ProductSummaryFieldsPricing"]


class ProductSummaryFieldsThumbnail(BaseModel):
    url: str
    alt: Optional[str]


class ProductSummaryFieldsPricing(BaseModel):
    onSale: Optional[bool]
    displayGrossPrices: bool
    priceRange: Optional["ProductSummaryFieldsPricingPriceRange"]


class ProductSummaryFieldsPricingPriceRange(BaseModel):
    start: Optional["ProductSummaryFieldsPricingPriceRangeStart"]
    stop: Optional["ProductSummaryFieldsPricingPriceRangeStop"]


class ProductSummaryFieldsPricingPriceRangeStart(BaseModel):
    gross: "ProductSummaryFieldsPricingPriceRangeStartGross"
    net: "ProductSummaryFieldsPricingPriceRangeStartNet"


class ProductSummaryFieldsPricingPriceRangeStartGross(BaseModel):
    amount: float
    currency: str


class ProductSummaryFieldsPricingPriceRangeStartNet(BaseModel):
    amount: float
    currency: str


class ProductSummaryFieldsPricingPriceRangeStop(BaseModel):
    gross: "ProductSummaryFieldsPricingPriceRangeStopGross"
    net: "ProductSummaryFieldsPricingPriceRangeStopNet"


class ProductSummaryFieldsPricingPriceRangeStopGross(BaseModel):
    amount: float
    currency: str


class ProductSummaryFieldsPricingPriceRangeStopNet(BaseModel):
    amount: float
    currency: str


class ProductDetailFields(ProductSummaryFields):
    description: Optional[Any]
    category: Optional["ProductDetailFieldsCategory"]
    productType: "ProductDetailFieldsProductType"
    defaultVariant: Optional["ProductDetailFieldsDefaultVariant"]


class ProductDetailFieldsCategory(BaseModel):
    id: str
    name: str
    slug: str


class ProductDetailFieldsProductType(BaseModel):
    id: str
    name: str


class ProductDetailFieldsDefaultVariant(BaseModel):
    id: str
    name: str
    sku: Optional[str]


class PromotionRuleFields(BaseModel):
    id: str
    name: Optional[str]
    cataloguePredicate: Optional[Any]
    orderPredicate: Optional[Any]
    rewardValue: Optional[Any]
    rewardValueType: Optional[RewardValueTypeEnum]
    rewardType: Optional[RewardTypeEnum]
    channels: Optional[list["PromotionRuleFieldsChannels"]]


class PromotionRuleFieldsChannels(BaseModel):
    id: str
    slug: str
    currencyCode: str


class PromotionSummaryFields(BaseModel):
    id: str
    name: str
    type_: Optional[PromotionTypeEnum] = Field(alias="type")
    startDate: Any
    endDate: Optional[Any]


class VariantSummaryFields(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    product: "VariantSummaryFieldsProduct"
    trackInventory: bool
    quantityAvailable: Optional[int]
    quantityLimitPerCustomer: Optional[int]
    pricing: Optional["VariantSummaryFieldsPricing"]
    assignedAttributes: list[
        Annotated[
            Union[
                "VariantSummaryFieldsAssignedAttributesAssignedAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedBooleanAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedNumericAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedPlainTextAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttribute",
                "VariantSummaryFieldsAssignedAttributesAssignedSwatchAttribute",
            ],
            Field(discriminator="typename__"),
        ]
    ]


class VariantSummaryFieldsProduct(BaseModel):
    id: str
    name: str
    slug: str
    isAvailable: Optional[bool]
    isAvailableForPurchase: Optional[bool]


class VariantSummaryFieldsPricing(BaseModel):
    onSale: Optional[bool]
    price: Optional["VariantSummaryFieldsPricingPrice"]
    priceUndiscounted: Optional["VariantSummaryFieldsPricingPriceUndiscounted"]


class VariantSummaryFieldsPricingPrice(BaseModel):
    gross: "VariantSummaryFieldsPricingPriceGross"
    net: "VariantSummaryFieldsPricingPriceNet"


class VariantSummaryFieldsPricingPriceGross(BaseModel):
    amount: float
    currency: str


class VariantSummaryFieldsPricingPriceNet(BaseModel):
    amount: float
    currency: str


class VariantSummaryFieldsPricingPriceUndiscounted(BaseModel):
    gross: "VariantSummaryFieldsPricingPriceUndiscountedGross"
    net: "VariantSummaryFieldsPricingPriceUndiscountedNet"


class VariantSummaryFieldsPricingPriceUndiscountedGross(BaseModel):
    amount: float
    currency: str


class VariantSummaryFieldsPricingPriceUndiscountedNet(BaseModel):
    amount: float
    currency: str


class VariantSummaryFieldsAssignedAttributesAssignedAttribute(BaseModel):
    typename__: Literal[
        "AssignedAttribute",
        "AssignedDateAttribute",
        "AssignedDateTimeAttribute",
        "AssignedFileAttribute",
        "AssignedMultiCategoryReferenceAttribute",
        "AssignedMultiCollectionReferenceAttribute",
        "AssignedMultiPageReferenceAttribute",
        "AssignedMultiProductReferenceAttribute",
        "AssignedMultiProductVariantReferenceAttribute",
        "AssignedSingleCategoryReferenceAttribute",
        "AssignedSingleCollectionReferenceAttribute",
        "AssignedSinglePageReferenceAttribute",
        "AssignedSingleProductReferenceAttribute",
        "AssignedSingleProductVariantReferenceAttribute",
        "AssignedTextAttribute",
    ] = Field(alias="__typename")
    attribute: "VariantSummaryFieldsAssignedAttributesAssignedAttributeAttribute"


class VariantSummaryFieldsAssignedAttributesAssignedAttributeAttribute(BaseModel):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedBooleanAttribute(BaseModel):
    typename__: Literal["AssignedBooleanAttribute"] = Field(alias="__typename")
    attribute: "VariantSummaryFieldsAssignedAttributesAssignedBooleanAttributeAttribute"
    boolean: Optional[bool]


class VariantSummaryFieldsAssignedAttributesAssignedBooleanAttributeAttribute(
    BaseModel
):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttribute(BaseModel):
    typename__: Literal["AssignedMultiChoiceAttribute"] = Field(alias="__typename")
    attribute: (
        "VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttributeAttribute"
    )
    choices: list[
        "VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttributeChoices"
    ]


class VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttributeAttribute(
    BaseModel
):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedMultiChoiceAttributeChoices(
    BaseModel
):
    name: Optional[str]
    slug: Optional[str]


class VariantSummaryFieldsAssignedAttributesAssignedNumericAttribute(BaseModel):
    typename__: Literal["AssignedNumericAttribute"] = Field(alias="__typename")
    attribute: "VariantSummaryFieldsAssignedAttributesAssignedNumericAttributeAttribute"
    number: Optional[float]


class VariantSummaryFieldsAssignedAttributesAssignedNumericAttributeAttribute(
    BaseModel
):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedPlainTextAttribute(BaseModel):
    typename__: Literal["AssignedPlainTextAttribute"] = Field(alias="__typename")
    attribute: (
        "VariantSummaryFieldsAssignedAttributesAssignedPlainTextAttributeAttribute"
    )
    text: Optional[str]


class VariantSummaryFieldsAssignedAttributesAssignedPlainTextAttributeAttribute(
    BaseModel
):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttribute(BaseModel):
    typename__: Literal["AssignedSingleChoiceAttribute"] = Field(alias="__typename")
    attribute: (
        "VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttributeAttribute"
    )
    choice: Optional[
        "VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttributeChoice"
    ]


class VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttributeAttribute(
    BaseModel
):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedSingleChoiceAttributeChoice(
    BaseModel
):
    name: Optional[str]
    slug: Optional[str]


class VariantSummaryFieldsAssignedAttributesAssignedSwatchAttribute(BaseModel):
    typename__: Literal["AssignedSwatchAttribute"] = Field(alias="__typename")
    attribute: "VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeAttribute"
    swatch: Optional[
        "VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeSwatch"
    ]


class VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeAttribute(BaseModel):
    id: str
    name: str
    slug: str


class VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeSwatch(BaseModel):
    name: Optional[str]
    slug: Optional[str]
    hexColor: Optional[str]
    file: Optional[
        "VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeSwatchFile"
    ]


class VariantSummaryFieldsAssignedAttributesAssignedSwatchAttributeSwatchFile(
    BaseModel
):
    url: str


ChannelSummaryFields.model_rebuild()
CustomerIdentityFields.model_rebuild()
CustomerMutationFields.model_rebuild()
OrderSummaryFields.model_rebuild()
ProductSummaryFields.model_rebuild()
ProductDetailFields.model_rebuild()
PromotionRuleFields.model_rebuild()
PromotionSummaryFields.model_rebuild()
VariantSummaryFields.model_rebuild()
