# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import CustomerIdentityFields


class Me(BaseModel):
    me: Optional["MeMe"]


MeMe = CustomerIdentityFields
Me.model_rebuild()
