# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel


class OrderOwnershipById(BaseModel):
    order: Optional["OrderOwnershipByIdOrder"]


class OrderOwnershipByIdOrder(BaseModel):
    id: str
    user: Optional["OrderOwnershipByIdOrderUser"]


class OrderOwnershipByIdOrderUser(BaseModel):
    id: str


OrderOwnershipById.model_rebuild()
OrderOwnershipByIdOrder.model_rebuild()
