# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Any, Optional

from .base_model import BaseModel
from .enums import FulfillmentStatus
from .fragments import (  # noqa: F401
    OrderSummaryFields,
    OrderSummaryFieldsChannel,
    OrderSummaryFieldsTotal,
)


class OrderById(BaseModel):
    order: Optional["OrderByIdOrder"]


class OrderByIdOrder(OrderSummaryFields):
    user: Optional["OrderByIdOrderUser"]
    shippingMethodName: Optional[str]
    subtotal: "OrderByIdOrderSubtotal"
    shippingPrice: "OrderByIdOrderShippingPrice"
    lines: list["OrderByIdOrderLines"]
    fulfillments: list["OrderByIdOrderFulfillments"]


class OrderByIdOrderUser(BaseModel):
    id: str


class OrderByIdOrderSubtotal(BaseModel):
    gross: "OrderByIdOrderSubtotalGross"
    net: "OrderByIdOrderSubtotalNet"


class OrderByIdOrderSubtotalGross(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderSubtotalNet(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderShippingPrice(BaseModel):
    gross: "OrderByIdOrderShippingPriceGross"
    net: "OrderByIdOrderShippingPriceNet"


class OrderByIdOrderShippingPriceGross(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderShippingPriceNet(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderLines(BaseModel):
    id: str
    productName: str
    variantName: str
    productSku: Optional[str]
    quantity: int
    quantityFulfilled: int
    quantityToFulfill: int
    unitPrice: "OrderByIdOrderLinesUnitPrice"
    totalPrice: "OrderByIdOrderLinesTotalPrice"


class OrderByIdOrderLinesUnitPrice(BaseModel):
    gross: "OrderByIdOrderLinesUnitPriceGross"
    net: "OrderByIdOrderLinesUnitPriceNet"


class OrderByIdOrderLinesUnitPriceGross(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderLinesUnitPriceNet(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderLinesTotalPrice(BaseModel):
    gross: "OrderByIdOrderLinesTotalPriceGross"
    net: "OrderByIdOrderLinesTotalPriceNet"


class OrderByIdOrderLinesTotalPriceGross(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderLinesTotalPriceNet(BaseModel):
    amount: float
    currency: str


class OrderByIdOrderFulfillments(BaseModel):
    id: str
    status: FulfillmentStatus
    trackingNumber: str
    created: Any
    lines: Optional[list["OrderByIdOrderFulfillmentsLines"]]


class OrderByIdOrderFulfillmentsLines(BaseModel):
    id: str
    quantity: int
    orderLine: Optional["OrderByIdOrderFulfillmentsLinesOrderLine"]


class OrderByIdOrderFulfillmentsLinesOrderLine(BaseModel):
    id: str


OrderById.model_rebuild()
OrderByIdOrder.model_rebuild()
OrderByIdOrderSubtotal.model_rebuild()
OrderByIdOrderShippingPrice.model_rebuild()
OrderByIdOrderLines.model_rebuild()
OrderByIdOrderLinesUnitPrice.model_rebuild()
OrderByIdOrderLinesTotalPrice.model_rebuild()
OrderByIdOrderFulfillments.model_rebuild()
OrderByIdOrderFulfillmentsLines.model_rebuild()
