# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import OrderErrorCode, OrderStatus


class OrderCancel(BaseModel):
    orderCancel: Optional["OrderCancelOrderCancel"]


class OrderCancelOrderCancel(BaseModel):
    order: Optional["OrderCancelOrderCancelOrder"]
    errors: list["OrderCancelOrderCancelErrors"]


class OrderCancelOrderCancelOrder(BaseModel):
    id: str
    number: str
    status: OrderStatus


class OrderCancelOrderCancelErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: OrderErrorCode


OrderCancel.model_rebuild()
OrderCancelOrderCancel.model_rebuild()
