# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import OrderSummaryFields


class OrdersByCustomer(BaseModel):
    user: Optional["OrdersByCustomerUser"]


class OrdersByCustomerUser(BaseModel):
    id: str
    orders: Optional["OrdersByCustomerUserOrders"]


class OrdersByCustomerUserOrders(BaseModel):
    edges: list["OrdersByCustomerUserOrdersEdges"]
    pageInfo: "OrdersByCustomerUserOrdersPageInfo"


class OrdersByCustomerUserOrdersEdges(BaseModel):
    cursor: str
    node: "OrdersByCustomerUserOrdersEdgesNode"


OrdersByCustomerUserOrdersEdgesNode = OrderSummaryFields


class OrdersByCustomerUserOrdersPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


OrdersByCustomer.model_rebuild()
OrdersByCustomerUser.model_rebuild()
OrdersByCustomerUserOrders.model_rebuild()
OrdersByCustomerUserOrdersEdges.model_rebuild()
