# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import FulfillmentStatus, OrderErrorCode, OrderStatus


class OrderFulfill(BaseModel):
    orderFulfill: Optional["OrderFulfillOrderFulfill"]


class OrderFulfillOrderFulfill(BaseModel):
    order: Optional["OrderFulfillOrderFulfillOrder"]
    fulfillments: Optional[list["OrderFulfillOrderFulfillFulfillments"]]
    errors: list["OrderFulfillOrderFulfillErrors"]


class OrderFulfillOrderFulfillOrder(BaseModel):
    id: str
    number: str
    status: OrderStatus


class OrderFulfillOrderFulfillFulfillments(BaseModel):
    id: str
    status: FulfillmentStatus
    trackingNumber: str
    lines: Optional[list["OrderFulfillOrderFulfillFulfillmentsLines"]]


class OrderFulfillOrderFulfillFulfillmentsLines(BaseModel):
    id: str
    quantity: int
    orderLine: Optional["OrderFulfillOrderFulfillFulfillmentsLinesOrderLine"]


class OrderFulfillOrderFulfillFulfillmentsLinesOrderLine(BaseModel):
    id: str


class OrderFulfillOrderFulfillErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: OrderErrorCode


OrderFulfill.model_rebuild()
OrderFulfillOrderFulfill.model_rebuild()
OrderFulfillOrderFulfillFulfillments.model_rebuild()
OrderFulfillOrderFulfillFulfillmentsLines.model_rebuild()
