# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import ProductDetailFields


class ProductBySlug(BaseModel):
    product: Optional["ProductBySlugProduct"]


ProductBySlugProduct = ProductDetailFields
ProductBySlug.model_rebuild()
