# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductUpdate(BaseModel):
    productUpdate: Optional["ProductUpdateProductUpdate"]


class ProductUpdateProductUpdate(BaseModel):
    product: Optional["ProductUpdateProductUpdateProduct"]
    errors: list["ProductUpdateProductUpdateErrors"]


class ProductUpdateProductUpdateProduct(BaseModel):
    id: str
    name: str
    slug: str


class ProductUpdateProductUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductUpdate.model_rebuild()
ProductUpdateProductUpdate.model_rebuild()
