# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import ProductSummaryFields


class ProductList(BaseModel):
    products: Optional["ProductListProducts"]


class ProductListProducts(BaseModel):
    edges: list["ProductListProductsEdges"]
    pageInfo: "ProductListProductsPageInfo"


class ProductListProductsEdges(BaseModel):
    cursor: str
    node: "ProductListProductsEdgesNode"


ProductListProductsEdgesNode = ProductSummaryFields


class ProductListProductsPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


ProductList.model_rebuild()
ProductListProducts.model_rebuild()
ProductListProductsEdges.model_rebuild()
