# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductCreate(BaseModel):
    productCreate: Optional["ProductCreateProductCreate"]


class ProductCreateProductCreate(BaseModel):
    product: Optional["ProductCreateProductCreateProduct"]
    errors: list["ProductCreateProductCreateErrors"]


class ProductCreateProductCreateProduct(BaseModel):
    id: str
    name: str
    slug: str


class ProductCreateProductCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductCreate.model_rebuild()
ProductCreateProductCreate.model_rebuild()
