# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Any, Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class ProductChannelListingUpdate(BaseModel):
    productChannelListingUpdate: Optional[
        "ProductChannelListingUpdateProductChannelListingUpdate"
    ]


class ProductChannelListingUpdateProductChannelListingUpdate(BaseModel):
    product: Optional["ProductChannelListingUpdateProductChannelListingUpdateProduct"]
    errors: list["ProductChannelListingUpdateProductChannelListingUpdateErrors"]


class ProductChannelListingUpdateProductChannelListingUpdateProduct(BaseModel):
    id: str
    channelListings: Optional[
        list[
            "ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings"
        ]
    ]


class ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings(
    BaseModel
):
    channel: "ProductChannelListingUpdateProductChannelListingUpdateProductChannelListingsChannel"
    isPublished: bool
    publishedAt: Optional[Any]
    visibleInListings: bool
    isAvailableForPurchase: Optional[bool]
    availableForPurchaseAt: Optional[Any]


class ProductChannelListingUpdateProductChannelListingUpdateProductChannelListingsChannel(
    BaseModel
):
    id: str
    slug: str
    currencyCode: str


class ProductChannelListingUpdateProductChannelListingUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


ProductChannelListingUpdate.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdate.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdateProduct.model_rebuild()
ProductChannelListingUpdateProductChannelListingUpdateProductChannelListings.model_rebuild()
