# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import ProductDetailFields


class ProductById(BaseModel):
    product: Optional["ProductByIdProduct"]


ProductByIdProduct = ProductDetailFields
ProductById.model_rebuild()
