# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import PromotionUpdateErrorCode
from .fragments import PromotionSummaryFields


class PromotionUpdate(BaseModel):
    promotionUpdate: Optional["PromotionUpdatePromotionUpdate"]


class PromotionUpdatePromotionUpdate(BaseModel):
    promotion: Optional["PromotionUpdatePromotionUpdatePromotion"]
    errors: list["PromotionUpdatePromotionUpdateErrors"]


PromotionUpdatePromotionUpdatePromotion = PromotionSummaryFields


class PromotionUpdatePromotionUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: PromotionUpdateErrorCode


PromotionUpdate.model_rebuild()
PromotionUpdatePromotionUpdate.model_rebuild()
