# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import PromotionCreateErrorCode
from .fragments import PromotionSummaryFields


class PromotionCreate(BaseModel):
    promotionCreate: Optional["PromotionCreatePromotionCreate"]


class PromotionCreatePromotionCreate(BaseModel):
    promotion: Optional["PromotionCreatePromotionCreatePromotion"]
    errors: list["PromotionCreatePromotionCreateErrors"]


PromotionCreatePromotionCreatePromotion = PromotionSummaryFields


class PromotionCreatePromotionCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: PromotionCreateErrorCode


PromotionCreate.model_rebuild()
PromotionCreatePromotionCreate.model_rebuild()
