# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import PromotionRuleUpdateErrorCode
from .fragments import PromotionRuleFields


class PromotionRuleUpdate(BaseModel):
    promotionRuleUpdate: Optional["PromotionRuleUpdatePromotionRuleUpdate"]


class PromotionRuleUpdatePromotionRuleUpdate(BaseModel):
    promotionRule: Optional["PromotionRuleUpdatePromotionRuleUpdatePromotionRule"]
    errors: list["PromotionRuleUpdatePromotionRuleUpdateErrors"]


PromotionRuleUpdatePromotionRuleUpdatePromotionRule = PromotionRuleFields


class PromotionRuleUpdatePromotionRuleUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: PromotionRuleUpdateErrorCode


PromotionRuleUpdate.model_rebuild()
PromotionRuleUpdatePromotionRuleUpdate.model_rebuild()
