# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import PromotionSummaryFields


class PromotionById(BaseModel):
    promotion: Optional["PromotionByIdPromotion"]


PromotionByIdPromotion = PromotionSummaryFields
PromotionById.model_rebuild()
