# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import PromotionRuleCreateErrorCode
from .fragments import PromotionRuleFields


class PromotionRuleCreate(BaseModel):
    promotionRuleCreate: Optional["PromotionRuleCreatePromotionRuleCreate"]


class PromotionRuleCreatePromotionRuleCreate(BaseModel):
    promotionRule: Optional["PromotionRuleCreatePromotionRuleCreatePromotionRule"]
    errors: list["PromotionRuleCreatePromotionRuleCreateErrors"]


PromotionRuleCreatePromotionRuleCreatePromotionRule = PromotionRuleFields


class PromotionRuleCreatePromotionRuleCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: PromotionRuleCreateErrorCode


PromotionRuleCreate.model_rebuild()
PromotionRuleCreatePromotionRuleCreate.model_rebuild()
