# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel


class StockList(BaseModel):
    stocks: Optional["StockListStocks"]


class StockListStocks(BaseModel):
    edges: list["StockListStocksEdges"]
    pageInfo: "StockListStocksPageInfo"


class StockListStocksEdges(BaseModel):
    node: "StockListStocksEdgesNode"


class StockListStocksEdgesNode(BaseModel):
    id: str
    warehouse: "StockListStocksEdgesNodeWarehouse"
    productVariant: "StockListStocksEdgesNodeProductVariant"
    quantity: int
    quantityAllocated: int


class StockListStocksEdgesNodeWarehouse(BaseModel):
    id: str


class StockListStocksEdgesNodeProductVariant(BaseModel):
    id: str


class StockListStocksPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


StockList.model_rebuild()
StockListStocks.model_rebuild()
StockListStocksEdges.model_rebuild()
StockListStocksEdgesNode.model_rebuild()
