# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import VariantSummaryFields


class VariantById(BaseModel):
    productVariant: Optional["VariantByIdProductVariant"]


VariantByIdProductVariant = VariantSummaryFields
VariantById.model_rebuild()
