# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class VariantUpdate(BaseModel):
    productVariantUpdate: Optional["VariantUpdateProductVariantUpdate"]


class VariantUpdateProductVariantUpdate(BaseModel):
    productVariant: Optional["VariantUpdateProductVariantUpdateProductVariant"]
    errors: list["VariantUpdateProductVariantUpdateErrors"]


class VariantUpdateProductVariantUpdateProductVariant(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    product: "VariantUpdateProductVariantUpdateProductVariantProduct"
    trackInventory: bool


class VariantUpdateProductVariantUpdateProductVariantProduct(BaseModel):
    id: str


class VariantUpdateProductVariantUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


VariantUpdate.model_rebuild()
VariantUpdateProductVariantUpdate.model_rebuild()
VariantUpdateProductVariantUpdateProductVariant.model_rebuild()
