# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import VariantSummaryFields


class VariantBySku(BaseModel):
    productVariant: Optional["VariantBySkuProductVariant"]


VariantBySkuProductVariant = VariantSummaryFields
VariantBySku.model_rebuild()
