# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class VariantChannelListingUpdate(BaseModel):
    productVariantChannelListingUpdate: Optional[
        "VariantChannelListingUpdateProductVariantChannelListingUpdate"
    ]


class VariantChannelListingUpdateProductVariantChannelListingUpdate(BaseModel):
    variant: Optional[
        "VariantChannelListingUpdateProductVariantChannelListingUpdateVariant"
    ]
    errors: list["VariantChannelListingUpdateProductVariantChannelListingUpdateErrors"]


class VariantChannelListingUpdateProductVariantChannelListingUpdateVariant(BaseModel):
    id: str
    sku: Optional[str]
    channelListings: Optional[
        list[
            "VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings"
        ]
    ]


class VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings(
    BaseModel
):
    channel: "VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsChannel"
    price: Optional[
        "VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsPrice"
    ]


class VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsChannel(
    BaseModel
):
    id: str
    slug: str
    currencyCode: str


class VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListingsPrice(
    BaseModel
):
    amount: float
    currency: str


class VariantChannelListingUpdateProductVariantChannelListingUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


VariantChannelListingUpdate.model_rebuild()
VariantChannelListingUpdateProductVariantChannelListingUpdate.model_rebuild()
VariantChannelListingUpdateProductVariantChannelListingUpdateVariant.model_rebuild()
VariantChannelListingUpdateProductVariantChannelListingUpdateVariantChannelListings.model_rebuild()
