# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class VariantStocksUpdate(BaseModel):
    productVariantStocksUpdate: Optional[
        "VariantStocksUpdateProductVariantStocksUpdate"
    ]


class VariantStocksUpdateProductVariantStocksUpdate(BaseModel):
    productVariant: Optional[
        "VariantStocksUpdateProductVariantStocksUpdateProductVariant"
    ]
    errors: list["VariantStocksUpdateProductVariantStocksUpdateErrors"]


class VariantStocksUpdateProductVariantStocksUpdateProductVariant(BaseModel):
    id: str
    sku: Optional[str]


class VariantStocksUpdateProductVariantStocksUpdateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    index: Optional[int]


VariantStocksUpdate.model_rebuild()
VariantStocksUpdateProductVariantStocksUpdate.model_rebuild()
