# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class VariantStocksCreate(BaseModel):
    productVariantStocksCreate: Optional[
        "VariantStocksCreateProductVariantStocksCreate"
    ]


class VariantStocksCreateProductVariantStocksCreate(BaseModel):
    productVariant: Optional[
        "VariantStocksCreateProductVariantStocksCreateProductVariant"
    ]
    errors: list["VariantStocksCreateProductVariantStocksCreateErrors"]


class VariantStocksCreateProductVariantStocksCreateProductVariant(BaseModel):
    id: str
    sku: Optional[str]


class VariantStocksCreateProductVariantStocksCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode
    index: Optional[int]


VariantStocksCreate.model_rebuild()
VariantStocksCreateProductVariantStocksCreate.model_rebuild()
