# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .enums import ProductErrorCode


class VariantCreate(BaseModel):
    productVariantCreate: Optional["VariantCreateProductVariantCreate"]


class VariantCreateProductVariantCreate(BaseModel):
    productVariant: Optional["VariantCreateProductVariantCreateProductVariant"]
    errors: list["VariantCreateProductVariantCreateErrors"]


class VariantCreateProductVariantCreateProductVariant(BaseModel):
    id: str
    name: str
    sku: Optional[str]
    product: "VariantCreateProductVariantCreateProductVariantProduct"
    trackInventory: bool


class VariantCreateProductVariantCreateProductVariantProduct(BaseModel):
    id: str


class VariantCreateProductVariantCreateErrors(BaseModel):
    field: Optional[str]
    message: Optional[str]
    code: ProductErrorCode


VariantCreate.model_rebuild()
VariantCreateProductVariantCreate.model_rebuild()
VariantCreateProductVariantCreateProductVariant.model_rebuild()
