# Generated by ariadne-codegen
# Source: src/agent_adapter_service/saleor/graphql

from typing import Optional

from .base_model import BaseModel
from .fragments import VariantSummaryFields


class VariantList(BaseModel):
    product: Optional["VariantListProduct"]


class VariantListProduct(BaseModel):
    id: str
    productVariants: Optional["VariantListProductProductVariants"]


class VariantListProductProductVariants(BaseModel):
    edges: list["VariantListProductProductVariantsEdges"]
    pageInfo: "VariantListProductProductVariantsPageInfo"


class VariantListProductProductVariantsEdges(BaseModel):
    cursor: str
    node: "VariantListProductProductVariantsEdgesNode"


VariantListProductProductVariantsEdgesNode = VariantSummaryFields


class VariantListProductProductVariantsPageInfo(BaseModel):
    hasNextPage: bool
    hasPreviousPage: bool
    startCursor: Optional[str]
    endCursor: Optional[str]


VariantList.model_rebuild()
VariantListProduct.model_rebuild()
VariantListProductProductVariants.model_rebuild()
VariantListProductProductVariantsEdges.model_rebuild()
